### ISSUE TITLE
Missing Subcommand For Yarn

### ISSUE THREAD

**Issue by hasanaburayyan** [cdkbook/feedback#1]
**Describe the issue**
Esling installation commands have a typo for installing with yarn. Missing subcommand `add`

**Where can we find it?**
4.2.4 ESLintCleanup
pg. 53
First code block

**Screenshots**
![image](https://user-images.githubusercontent.com/45375125/144633672-a91e8040-3542-4535-bebc-4a42a3cafc60.png)

**Comment by mbonig** [comment]
Thank you for catching this. It has been fixed and will go out in the next release.
