### ISSUE TITLE
Grammar issue

### ISSUE THREAD

**Issue by Z11** [cdkbook/feedback#10]
**Describe the bug**
In “1.3.2 CDK vs terraform”

 “Recent updates to Terraform have added support for looping
constructs, but it can still slow to adopt other features. “

Should be:

“ Recent updates to Terraform have added support for looping
constructs, but it can still [be] slow to adopt other features. “

**Where can we find it?**

1.3.2 CDK vs terraform

**Screenshots**
![image](https://user-images.githubusercontent.com/4098471/145262017-12a92094-29b6-41c5-ab7f-4b78bfda6214.png)

**Additional context**
None

**Comment by SathyaBhat** [comment]
Thanks for the report! I have fixed this and will go in the next release.
