### ISSUE TITLE
Use of "way" instead of "away"

### ISSUE THREAD

**Issue by mbacchi** [cdkbook/feedback#11]
**Describe the bug**
The description how the CDK uses abstraction says "abstracts way" and I imagine you mean "abstracts away".

**Where can we find it?**
Page 19, paragraph 1, sentence 1 of the-cdk-book-python.pdf

**Screenshots**

**Additional context**

**Comment by SathyaBhat** [comment]
thank you for reporting this! this has been fixed and changes will go with the next release
