### ISSUE TITLE
Missing Chapter Insert For Context Variables

### ISSUE THREAD

**Issue by hasanaburayyan** [cdkbook/feedback#2]
**Describe the bug**
Plain text `[insert here] chapter` actual chapter not inserted. This paragraph is giving a glimpse into context variables and that they would be covered more later on in the book. I presume the referenced chapter was supposed to be Chapter 7.1.1 (not sure though)

**Where can we find it?**
5.1.4 cdk.json
pg. 57
last paragraph

**Screenshots**
![image](https://user-images.githubusercontent.com/45375125/144635405-be0eddfc-2097-4f2c-ab99-67319f7b7de1.png)

**Additional context**

**Comment by mbonig** [comment]
Thank you for catching this. It has been fixed and will go out in the next release.
