### ISSUE TITLE
Typo in Chapters 7.13, 8.4.1, 11.4.5, 12

### ISSUE THREAD

**Issue by brentcetinich** [cdkbook/feedback#25]
A few typos, I am no English scholar so I could be wrong ;) 

**7.1.3**
FROM don't let us specific more complex types
TO      don't let us specifi**y** more complex types

FROM **then the stack might either fail**.
TO      **then the stack might fail**.

**8.4.1**
Problem sentence: will be in a file called **index.py** under the lambda directory
Suggested action: The directory tree printout below above sentence does not have a **index.py** inside the lambda directory instead it has an app.py (maybe I didn't get it or its not related)

**11.4.5**
FROM: mutate the pipeline anymore **ant** for many small assets,
TO:      mutate the pipeline anymore **and** for many small assets,

**12**
FROM: direct control, or **prioritizes** don't allow you to replace that code
TO:      direct control, or **priorities** don't allow you to replace that code

I suggest changing **props** to **properties** in this chapter when its not a code reference.

**Comment by SathyaBhat** [comment]
Thank you for pointing these out!
