### ISSUE TITLE
Python example on p. 217 is not valid Python and does not work

### ISSUE THREAD

**Issue by jamesshapiro** [cdkbook/feedback#26]
**Describe the bug**
Code is not written in Python for Python version of the book and the code does not work

**Where can we find it?**
217

**Screenshots**

<img width="419" alt="cdk-scr" src="https://user-images.githubusercontent.com/1048420/151159315-fab76abc-e7df-4400-a7cd-e9ce7c5df43f.png">

**Additional context**
Code reads as follows:

```python
  def visit(self, scope):
    if scope instanceof s3.CfnBucket:
      if typeof scope.bucketEncryption == "undefined":
        scope.bucket_encryption = {
          "server_side_encryption_configuration": [{
            "server_side_encryption_by_default": {
              "sse_algorithm": "AES256"
            }
          }]
        }
```

A working implementation would be as follows:
```python
    def visit(self, scope):
        if isinstance(scope, s3.CfnBucket):
            if type(scope.bucket_encryption) == type(None):
                scope.bucket_encryption = {
                    "serverSideEncryptionConfiguration": [
                        {
                            "serverSideEncryptionByDefault": {
                                "sseAlgorithm": "AES256"
                            }
                        }
                    ]
                }
```

**Comment by mbonig** [comment]
Thanks for pointing this out. We're leveraging jsii-rosetta for doing these conversions and don't have an easy way to override its conversions. I'll dig in more and see what I can do.
