### ISSUE TITLE
Incorrect fs API call on TS example

### ISSUE THREAD

**Issue by adriangabardo** [cdkbook/feedback#28]
**Describe the issue**
On this specific example, the description is `To make this more deterministic this code would be rewritten slightly to save the data to a file:`, but then on the code example the call being made is `fs.readFileSync` instead of `fs.writeFileSync`.

**Where can we find it?**
Page 113, Section 7.2. Dynamic Management.

Erroneous code:
```ts
axios.get('https://someconfig.mycompany.com/dev')
      .then(devConfig => {
          fs.readFileSync('./env/dev.json', devConfig);
      });
```

Proposal:
```ts
axios.get('https://someconfig.mycompany.com/dev')
      .then(devConfig => {
          fs.writeFileSync('./env/dev.json', devConfig);
      });
```

**Screenshots**
<img width="856" alt="Screen Shot 2022-05-06 at 2 33 30 pm" src="https://user-images.githubusercontent.com/39781121/167067571-4081eb1c-bf69-4106-af84-fba90ce3c1ff.png">

**Comment by mbonig** [comment]
Thanks for catching this. I've made the update.

**Comment by adriangabardo** [comment]
Think we are good to close this one. Cheers!
