### ISSUE TITLE
Misspell "can"

### ISSUE THREAD

**Issue by hasanaburayyan** [cdkbook/feedback#3]
**Describe the bug**
The word `can` was spelled `cam`

**Where can we find it?**
8.2.3 Customizing the CloudFormation template
pg. 126
second paragraph

**Screenshots**
![image](https://user-images.githubusercontent.com/45375125/144636011-32d25b34-c457-48d8-a03f-6283b360d1cb.png)

**Additional context**

**Comment by mbonig** [comment]
Thank you for catching this. It has been fixed and will go out in the next release.
