### ISSUE TITLE
Physical copy

### ISSUE THREAD

**Issue by jlosito** [cdkbook/feedback#30]
**Is there something you'd like to see covered in The CDK Book?**
I would really love to have a physical copy of the book. While ebooks are great, I personally would rather have a physical copy.

**Comment by mbonig** [comment]
Thanks for commenting. We looked into physical printing and it wasn't very cost effective. However, the license you get when you buy allows you to print a copy for yourself. A local printer should be able to square you away. If there are concerns about copyright and whether you can, let us know (add a comment to this issue)
