### ISSUE TITLE
Possible Unremoved Awaiting Feedback Text

### ISSUE THREAD

**Issue by hasanaburayyan** [cdkbook/feedback#4]
**Describe the bug**
This one I am not sure of, I dont assume the message here is geared towards the readers, rather the authors during writing.

Section talking about deterministic software contains all caps text `(GETTING FEEDBACK ON THIS)` when making a statement about fundamental principles of CDK.

**Where can we find it?**
7.1.3 Less Static-y Files
pg. 110

**Screenshots**
![image](https://user-images.githubusercontent.com/45375125/144636770-e8b781b6-5c4f-4ba0-9cc9-c202215cc70f.png)

**Additional context**

**Comment by mbonig** [comment]
Thank you for catching this. It has been fixed and will go out in the next release.
