### ISSUE TITLE
Field Named createBy

### ISSUE THREAD

**Issue by hasanaburayyan** [cdkbook/feedback#5]
**Describe the bug**
When talking about additional fields example uses `createBy` instead of `createdBy`

**Where can we find it?**
9.3.2 Use Case 2 - Lambda-backed API Gateway
pg. 180
Second paragraph

**Screenshots**
![image](https://user-images.githubusercontent.com/45375125/144642734-2f2a7cac-3bad-491d-99cf-7efdc125d124.png)

**Additional context**

**Comment by mbonig** [comment]
Thank you for catching this. It has been fixed and will go out in the next release.
