### ISSUE TITLE
Code Example Does Not Match Description

### ISSUE THREAD

**Issue by hasanaburayyan** [cdkbook/feedback#7]
**Describe the issue**
When mocking the axios framework, it looks like the intent is to show the helper function method that would specify which framework to use. However the code block that is shown is a duplicate of the test block example above.

**Where can we find it?**
9.4.3 Typescript/Javascript
pg. 196
Second code block

**Screenshots**
![image](https://user-images.githubusercontent.com/45375125/144649420-5aadfae6-8fb9-41bf-bf18-6b73e1bbc2c2.png)

**Additional context**

**Comment by mbonig** [comment]
Thanks, fix will go out in next release.
